### ISSUE TITLE
Large memory usage

### ISSUE THREAD

**Issue by fengkaijia** [kdeldycke/maildir-deduplicate#19]
Hi,

I'm running ```maildir-deduplicate``` on a very large maildir (> 8GB) on Debian 7.0 and I found that ```maildir-deduplicate``` is eating large sum of memory, almost the same size as of the maildir.

It look's like ```maildir-deduplicate``` will generally load every mail file into memory which will cause a lot of pain in case of a very large mailbox. It would be better if we just store a ```hash``` or ```message-id``` in memory.

**Comment by aspiers** [comment]
Sounds like a valid bug to me.  Maybe we need to clear up some unneeded references somewhere.

**Comment by bakoonin** [comment]
Hi there,

Just tried deduplicating a gigantic maildir folder containing a silly number of duplicates, and watched mdedup eat more than 12 GB RAM before it was killed by the kernel:

`$ du -csh mailarchive`
73G     mailarchive
73G     total

`$ ls -1 mailarchive/new/|wc`
1745032 1745032 91434121

`$ time mdedup deduplicate --strategy older mailarchive`

Processing 1745032 mails in /home/bakoonin/mailarchive
Killed

real    70m20.338s
user    12m56.656s
sys     1m1.008s

`$ grep Killed /var/log/syslog`
Jul 21 20:56:21 U1404 kernel: [284836.012230] Killed process 16939 (mdedup) total-vm:12076780kB, anon-rss:12037232kB, file-rss:0kB
`

Not exactly on topic, but plan B is importing all emails into a single mbox file that hopefully can be deduplicated using formail:

`formail -D 100000000 idcache < mailarchive.old.mbox -s > mailarchive.new.mbox`

**Comment by kdmurray91** [comment]
I'm hitting the same bug. Is there a fix planned soon? Do you need any assistance or debugging info?

**Comment by kdeldycke** [comment]
Fixed in 62e33f414424ca35bc775accbd28c0ce376ab11b .
