### ISSUE TITLE
Unclear how to install

### ISSUE THREAD

**Issue by aspiers** [kdeldycke/maildir-deduplicate#21]
Since transitioning from a simple script to a package, it's not at all clear how to use this any more.  README.rst is missing any installation instructions, and the usage text begins:

    Usage: __init__.py [OPTIONS] [MAILDIR [MAILDIR ...]]

which is obviously wrong.

**Comment by aspiers** [comment]
@kdeldycke Please can you clarify?  I can't use the new version until I understand this.

**Comment by micressor** [comment]
Me too. I'd like to use this script, but how?

**Comment by jult** [comment]
Same here. +1. How to even run this? I tried to do ./__init__.py but it yields

import: unable to open X server `' @ error/import.c/ImportImageCommand/368.
import: unable to open X server `' @ error/import.c/ImportImageCommand/368.
import: unable to open X server `' @ error/import.c/ImportImageCommand/368.
import: unable to open X server `' @ error/import.c/ImportImageCommand/368.
import: unable to open X server `' @ error/import.c/ImportImageCommand/368.
import: unable to open X server `' @ error/import.c/ImportImageCommand/368.
./__init__.py: line 26: from: command not found
./__init__.py: line 27: from: command not found
./__init__.py: line 28: from: command not found
./__init__.py: line 29: from: command not found
./__init__.py: line 31: __version__: command not found
./__init__.py: line 33: syntax error near unexpected token `('
./__init__.py: line 33: `class InsufficientHeadersError(Exception):'

so yeah. Way to go on the documentation here. So sad!

**Comment by kdeldycke** [comment]
OK guys, I get the message ! I agree with all of you: the whole package is quite broken and the associated documentation is heavily user-unfriendly.

I'm going to refactor the package in the next few weeks. Stay tuned.

**Comment by jult** [comment]
Sad to hear that. Wanted to use it today ;-) Do you have an older script doing the same somewhere I can use on some dovecot Maildir mess with dupes?

**Comment by aspiers** [comment]
@jult just do what I'm doing and use the version from before the big change. It's easy to find in the git history.

**Comment by jult** [comment]
OK, I will. Just found another good option to look at: http://wiki2.dovecot.org/Tools/Doveadm/Deduplicate

**Comment by kdeldycke** [comment]
As @aspiers said: you'd better use an old version from the git history.

Here is the latest version before the packaging attempt: https://github.com/kdeldycke/maildir-deduplicate/tree/851b2e9f166b22ada55538bd58d3fc81f51dbaaf

**Comment by aspiers** [comment]
@kdeldycke maybe you could tag that commit for convenience, or even create a `stable`branch off it.

The `doveadm` command seems to do extremely naive deduplication based on the help text for the `-m` switch.

**Comment by jult** [comment]
So, how does one run the old one? I found that it works for the current dir and looks for /cur /new etc. but would be good to know if it fucks up or runs dry etc. I'm on a linux machine, with python.

**Comment by kdeldycke** [comment]
@aspiers : Just did that. Branch is now called `legacy` and the home page of the project now points to that branch: https://github.com/kdeldycke/maildir-deduplicate/tree/legacy

**Comment by jult** [comment]
Old script runs, but is not very clear on what it's doing. It did give me something wrong after a run on some Maildir:
    Traceback (most recent call last):
      File "./maildir-deduplicate.py", line 204, in <module>
        main()
      File "./maildir-deduplicate.py", line 200, in main
       duplicates = findDuplicates(mails_by_hash, delete)
     File "./maildir-deduplicate.py", line 107, in findDuplicates
       subject, count = re.subn('\s+', ' ', subject)
     File "/usr/lib64/python2.6/re.py", line 162, in subn
       return _compile(pattern, 0).subn(repl, string, count)
    TypeError: expected string or buffer

**Comment by kdeldycke** [comment]
@jult Now that's another issue. I created a dedicated ticket at: https://github.com/kdeldycke/maildir-deduplicate/issues/25 . Please continue the discussion over there.

**Comment by kdeldycke** [comment]
Installation instructions added in commit 324d4471154854fca28ca0f1e25e19aa023d9ef2. The remaining work required to make the script useable again is now ported by #26.

**Comment by jult** [comment]
You closed this, but, even though the -h works, it doesn't say a thing about stacking options.
What happens if you stack, say -dOns, does that work?

**Comment by kdeldycke** [comment]
@jult don't worry, the CLI is supposed to stop and return an error message if a set of options is not allowed.
