### ISSUE TITLE
Does not run on Python 2.6.6

### ISSUE THREAD

**Issue by reedog117** [kdeldycke/maildir-deduplicate#29]
Not sure if a minimum Python version needs to be specified, but I can't even run ```mdedup --help``` without running into an error when it's installed on CentOS 6.x via PyPi.

```
Traceback (most recent call last):
  File "usr/bin/mdedup", line 7, in <module>
    from maildir_deduplicate.cli import cli
  File "/usr/lib/python2.6/site-packages/maildir_deduplicate/cli.py", line 94, in <module>
    DEFAULT_SIZE_DIFFERENCE_THRESHOLD))
ValueError: zero length field name in format
```

**Comment by kdeldycke** [comment]
Yes, `format()` is only available in Python 2.7. See: http://stackoverflow.com/a/5447119

And this package is only tested on Python 2.7:
https://github.com/kdeldycke/maildir-deduplicate/blob/develop/.travis.yml#L7
https://github.com/kdeldycke/maildir-deduplicate/blob/develop/setup.py#L79

I'm going to close this issue for now unless there is someone out there who's motivated enough to work on backporting the code to older Python.
