### ISSUE TITLE
No graceful handling of crashes/further Unicode issues

### ISSUE THREAD

**Issue by EvilRenegade** [kdeldycke/maildir-deduplicate#39]
Hi,

I've had a number of unhandled exceptions related to all the Unicode issues (#32, #33, #35).
I accidentally originally installed the Python 2 version of maildir-deduplicate, and it _is_ better on the Python 3 version, but several of my mails still manage to cause unhandled exceptions.

These seem to predominantly be mails which have been wrongly encoded - which _should_ have been marked and encoded as UTF, but haven't been. 
Python does seem to recognize something is off and shift those characters to 0xFFFD, the [Unicode Replacement Character](https://en.wikipedia.org/wiki/Specials_%28Unicode_block%29#Replacement_character), but nevertheless fails with `UnicodeEncodeError: 'ascii' codec can't encode character '\ufffd' in position 13: ordinal not in range(128)`.

I understand that maildir-deduplicate can't magically know in what particular way a fucked up mail was fucked up and treat the wrong data correctly. That mail was encoded wrongly and that's my problem, not maildir-deduplicate's.

What's annoying me is the **lack of handling on the exception**.
There are over 4000 mails in that maildir, the vast majority of which are perfectly RFC-compliant, and I can't parse that folder because a handful of mails are screwed and maildir-deduplicate doesn't properly handle it.

I don't expect the software to magically fix broken input. But if I have 1 broken e-mail out of a thousand, I _do_ expect it to **just skip the broken one and do the other 999**.

Unicode-errors are the most common ones, but it's not limited to that: I've also had one run fail on me because of a missing header in a collection: 

```
  File "/usr/local/lib/python3.4/dist-packages/maildir_deduplicate/deduplicate.py", line 355, in get_lines_from_message_body
    header_text, sep, body = message.as_string().partition("\n\n")
  File "/usr/lib/python3.4/email/message.py", line 159, in as_string
    g.flatten(self, unixfrom=unixfrom)
  File "/usr/lib/python3.4/email/generator.py", line 112, in flatten
    self._write(msg)
  File "/usr/lib/python3.4/email/generator.py", line 178, in _write
    self._dispatch(msg)
  File "/usr/lib/python3.4/email/generator.py", line 211, in _dispatch
    meth(msg)
  File "/usr/lib/python3.4/email/generator.py", line 269, in _handle_multipart
    g.flatten(part, unixfrom=False, linesep=self._NL)
  File "/usr/lib/python3.4/email/generator.py", line 112, in flatten
    self._write(msg)
  File "/usr/lib/python3.4/email/generator.py", line 178, in _write
    self._dispatch(msg)
  File "/usr/lib/python3.4/email/generator.py", line 211, in _dispatch
    meth(msg)
  File "/usr/lib/python3.4/email/generator.py", line 269, in _handle_multipart
    g.flatten(part, unixfrom=False, linesep=self._NL)
  File "/usr/lib/python3.4/email/generator.py", line 112, in flatten
    self._write(msg)
  File "/usr/lib/python3.4/email/generator.py", line 186, in _write
    msg.replace_header('content-transfer-encoding', munge_cte[0])
  File "/usr/lib/python3.4/email/message.py", line 559, in replace_header
    raise KeyError(_name)
KeyError: 'content-transfer-encoding'
```

The fact that you're using exceptions at all is good. But not handling exceptions is bad, and not handling exceptions in a program designed for batch processing is just wrong.

I will try to hack something up for my local installation and I will submit a patch if I succeed, but this is ultimately a question of design mentality: You are currently placing the burden of dealing with problematic input on the user. You're essentially saying "this program will work fine..._if_ you made sure those 10000 mails you want to scan are all RFC-compliant in advance!".

I do believe it would greatly increase the usefulness of this tool if you expected it to fail on some messages and dealt with that gracefully, instead of just crashing back into the terminal in the middle of processing.

Thank you for your efforts. I haven't actually gotten this tool to work yet, but thanks to your work, I at least have a shot at dealing with these mails. I do appreciate the time you're investing.

**Comment by aspiers** [comment]
Very well said! Kevin is doing a great job maintaining this extremely handy piece of software, but robust exception handling would be a wonderful addition to the project! And it should not be hard to do at all. Thanks for the suggestion!

**Comment by EvilRenegade** [comment]
I have gone the cheapest possible route and simply wrapped the processing loop in a catch-all handler.
That's generally not the best practice, but it does improve the situation in so far as that the loop keeps running instead of aborting.

Disclaimer: I have not yet done a production run (i.e. with deletion), because of the ambiguities detailed in #40. 

However, the patch I have applied is attached. It's done against the current pip version (1.3.0).
I know I could do a pull request, but that would have required setting up an entire dev environment for this script, rather than just fixing the installation I already have.
Sorry, but that's the way it is.

With the patch as attached, exceptions get written to stderr in the format of
```
# # # # # # # EXCEPTION # # # # # # #
Type: <class 'KeyError'>
Value: 'content-transfer-encoding'
Files parsed: ['/home/renegade/[REDACTED]', '/home/renegade/[REDACTED]']
# # # # # # # # # # # # # # # # # # #
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/maildir_deduplicate/deduplicate.py", line 249, in run
    sorted_messages_size = self.size_sort(messages)
  File "/usr/local/lib/python3.4/dist-packages/maildir_deduplicate/deduplicate.py", line 347, in size_sort
    body = cls.get_lines_from_message_body(message)
  File "/usr/local/lib/python3.4/dist-packages/maildir_deduplicate/deduplicate.py", line 360, in get_lines_from_message_body
    header_text, sep, body = message.as_string().partition("\n\n")
  File "/usr/lib/python3.4/email/message.py", line 159, in as_string
    g.flatten(self, unixfrom=unixfrom)
  File "/usr/lib/python3.4/email/generator.py", line 112, in flatten
    self._write(msg)
  File "/usr/lib/python3.4/email/generator.py", line 178, in _write
    self._dispatch(msg)
  File "/usr/lib/python3.4/email/generator.py", line 211, in _dispatch
    meth(msg)
  File "/usr/lib/python3.4/email/generator.py", line 269, in _handle_multipart
    g.flatten(part, unixfrom=False, linesep=self._NL)
  File "/usr/lib/python3.4/email/generator.py", line 112, in flatten
    self._write(msg)
  File "/usr/lib/python3.4/email/generator.py", line 178, in _write
    self._dispatch(msg)
  File "/usr/lib/python3.4/email/generator.py", line 211, in _dispatch
    meth(msg)
  File "/usr/lib/python3.4/email/generator.py", line 269, in _handle_multipart
    g.flatten(part, unixfrom=False, linesep=self._NL)
  File "/usr/lib/python3.4/email/generator.py", line 112, in flatten
    self._write(msg)
  File "/usr/lib/python3.4/email/generator.py", line 186, in _write
    msg.replace_header('content-transfer-encoding', munge_cte[0])
  File "/usr/lib/python3.4/email/message.py", line 559, in replace_header
    raise KeyError(_name)
KeyError: 'content-transfer-encoding'
```
and the code skips to the next item in the loop.

Since I just plain wrapped the existing code, I am not giving the slightest guarantee that I'm not skipping necessary clean up code between loops.

If you want to save the new import, you can take out the import, the assignment line and cut down the format string, so that it only displays the current set of processed files. The Logging module will still place the exception info afterwards.

Personally, I like to have the quick overview.

Attachment is a .txt because GitHub, of all places, blocks the .patch file extension. -_-

[maildir_deduplicate_issue_39.txt](https://github.com/kdeldycke/maildir-deduplicate/files/453431/maildir_deduplicate_issue_39.txt)

**Comment by aspiers** [comment]
Cool, thanks!

> I know I could do a pull request, but that would have required setting up an entire dev environment for this script

I'm probably missing something, but isn't this as simple as clicking the fork button, then doing a `git clone` from it, copying the changes from your installation, `git commit && git push` and then clicking the pull request button?  Actually, it's even easier than that, because you can edit files directly from within the web UI ...

But if you don't have time I totally understand. Just thought I'd mention on the off-chance you're new to creating PRs and this helps ...

**Comment by EvilRenegade** [comment]
It's not as simple as that as there isn't actually any documentation on how to get this stuff running from the repo.
The only installation instructions I see are a pip one-liner.
I'm certain I could figure it out, but why go through the trouble if I already have the files?

And even then: 

1. fork
2. clone
3. edit
4. commit
5. push
6. request

are more steps than

1. edit
2. diff
3. upload

If there were documentation on how I could run the script directly from a working copy and I didn't already have _two_ versions of this installed (Python 2 and Python 3), I may have gone that route.

But I really just need my existing installation to run.

**Comment by aspiers** [comment]
Sorry if I wasn't clear. My point was that you don't need to get this stuff running from the repo.  Your diff only affects one file, so if you've already tested the changes with your installation, it's pretty safe to assume that simply copying those changes to the git repo will be good enough. And this can be done simply by clicking the edit button on [this page](https://github.com/kdeldycke/maildir-deduplicate/blob/develop/maildir_deduplicate/deduplicate.py), copying and pasting the entire modified version as a replacement for the existing one, and then clicking 2 or 3 more buttons to submit the PR.  (OK, it would be nice to also type a short commit message.)

Of course you are under absolutely no obligation to do this. The only reason that I am suggesting it is that it's *far* easier to collaboratively review a patch using github's web UI than by making references to an attached text file.  For example, the PR UI lets reviewers comment inline on a line-by-line basis, which is super useful.  But again, if you don't have time for this, that's absolutely fine.  In fact I could submit a PR based on the diff for you if you prefer.

**Comment by EvilRenegade** [comment]
xD It was originally a question of effort, but considering that, in the time I spent replying to you, I could have submitted a pull request, I'll go ahead and do so. :P

**Comment by EvilRenegade** [comment]
The request is there, but it's failing the build because it doesn't like my style.
I'm not going to argue with a machine about whether we should still adhere to a 80 char width limit.

**Comment by aspiers** [comment]
Well, [there are very good reasons for limiting the line length](https://www.python.org/dev/peps/pep-0008/#maximum-line-length), but like I said in the PR, if you don't want to fix it, I or someone else can do it.

**Comment by EvilRenegade** [comment]
The Python people also think that abusing exceptions for control flow is superb programming.
The language is great, but the opinion heads are nutcases.

Anyway, I fixed my style issue, I fixed some additional style issues, and now the next system is failing.
I don't have time for this shit.
I was just trying to offer a crude, minimal patch. I'm not going to write tests or whatever it wants from me now.

**Comment by aspiers** [comment]
That's fine, we've already made progress here.

**Comment by bonds** [comment]
Just wanted to say into trouble deduping my huge mail collection because of this too, I'll be following along with great interest, and thank you for considering this issue! I'm very glad a tool like this exists, it helps solves a big problem for folks like us that curate our own email archives.

**Comment by zx80** [comment]
Yep, there is a little bit of a pain to run into these issues.
Mostly I have unadvertised latin-1 encoding in headers.
I tried -i but got missing message-id then.
Oldest mails over 25 year old...
Thanks for making this tool more resilient!
