### ISSUE TITLE
Serious documentation issue: Strategies reversed

### ISSUE THREAD

**Issue by EvilRenegade** [kdeldycke/maildir-deduplicate#40]
The documentation both on GitHub and in the script states:

>  Removal strategies for each set of mail duplicates:
>      - older: remove all but the newest message (determined by ctime).
>      - newer: remove all but the oldest message (determined by ctime).

I am running with ` --strategy newer`, so I would have expected the oldest message to survive.
Nevertheless, the debug output states:

> Subject: Test 2
> left    1 147268**5012**.4187646 /home/renegade/[REDACTED]
> removed 2 1472685012.3827646 /home/renegade/[REDACTED]
> removed 3 1472680756.5782707 /home/renegade/[REDACTED]
> removed 4 147268**0756**.5702705 /home/renegade/[REDACTED]

147268**5012** is 2016-08-31T**23:10:12**+00:00
147268**0756** is 2016-08-31T**21:59:16**+00:00

The message marked as "4" above is quite clearly the oldest message and should have survived, according to the documentation. Instead, the newest message was chosen.

This is how Python sorting orders the values:
```
>>> test=[1472685012.3827646,1472680756.5782707,1472680756.5702705,1472685012.4187646]
>>> test.sort()
>>> test
[1472680756.5702705, 1472680756.5782707, 1472685012.3827646, 1472685012.4187646]
>>> test.sort(reverse=True)
>>> test
[1472685012.4187646, 1472685012.3827646, 1472680756.5782707, 1472680756.5702705]
```

It is quite obvious that, for the result above, maildir-deduplicate chose the `reverse=True` sorting argument.
```python
    def time_sort(messages, old_to_new):
        ctimes = []
        for mail_file, message in messages:
            ctime = os.path.getctime(mail_file)
            ctimes.append((ctime, mail_file, message))

        ctimes.sort(reverse=old_to_new)

        return ctimes
```
The code chooses whether to reverse sort depending on the second argument to `time_sort`.

```python
                if self.strategy == OLDER:
                    sorted_messages_ctime = self.time_sort(messages, False)
                elif self.strategy == NEWER:
                    sorted_messages_ctime = self.time_sort(messages, True)
```
If the strategy `NEWER` is chosen, the code chooses _reverse_ sorting, which results in the largest number to be sorted first. Since Unix timestamps are ever-increasing, the largest number is the newest (youngest) date.
The code later chooses the survivor by simply skipping the first record:
```python
        for i, duplicate in enumerate(duplicate_set):
            size, mail_file, message = duplicate
            if self.strategy in [SMALLER, OLDER, NEWER]:
                if i > 0:
                    doomed[mail_file] = 1
```

Unless I'm missing something major here, **the actual deletion behaviour of the code is the exact opposite of what the documentation states!**

The documentation is laid out in the sense of "which messages should I delete?".
The code operates in the sense of "which message should I keep?".

**Comment by kdeldycke** [comment]
Oh yes... The way strategies are both implemented and advertised are far for user-friendly. I'm going to try to fix that but it might involve some kind of refactoring.
