### ISSUE TITLE
maildir-deduplicate fails with ValueError: year out of range

### ISSUE THREAD

**Issue by jepler** [kdeldycke/maildir-deduplicate#54]
The message in question has the following header:
~~~~
Date: Thu, 13 Dec 101 15:30 WET
~~~~
it was probably produced in 2001 with a non-y2k compliant mailer; a received header has 'Thu, 13 Dec 2001 15:34:58 -0600'.

**Comment by kdeldycke** [comment]
Fix has been merged upstream by the way of: https://github.com/kdeldycke/maildir-deduplicate/pull/56
