### ISSUE TITLE
Assertion error: Kept != Unique + Duplicates

### ISSUE THREAD

**Issue by salexan2001** [kdeldycke/maildir-deduplicate#57]
Running `mdedup deduplicate -n -s delete-older -t date-header .` (from my maildir folder) raises an assertion error:
```
(...)

  File "/home/salexan/.local/lib/python3.6/site-packages/maildir_deduplicate/cli.py", line 209, in deduplicate
    dedup.report()
  File "/home/salexan/.local/lib/python3.6/site-packages/maildir_deduplicate/deduplicate.py", line 597, in report
    self.stats['mail_duplicates'])
AssertionError
```

This is related to the following numbers in the stats:
Kept       │     3215 │
Unique     │     2416 │
Duplicates │     3215 │

**Comment by mistrey** [comment]
Same here with Python 2.7

**Comment by rbnvrw** [comment]
Is there a fix available for this yet? I still get the same error after using the latest master version.

**Comment by kdeldycke** [comment]
The fix has been merged upstream by the merge of https://github.com/kdeldycke/maildir-deduplicate/pull/64
